
version: '3'

services:
  db:
    image: postgres:14
    container_name: stock_g_db
    environment:
      - POSTGRES_USER=foo
      - POSTGRES_PASSWORD=bar
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stock_g_app
    volumes:
      - './server:/usr/src/app/server'
      - ./client:/usr/src/app/client
      - venv:/usr/src/app/.venv
    depends_on:
      - db
    ports:
      - 5000:5000
    env_file:
      - .env



volumes:
  db_data:
  venv:
    #driver: local