[tool.poetry]
name = "proken2022-ccc-server"
version = "0.0.1"
description = "CCCの作品"
authors = ["Maruo.S <raspi-maru2004@outlook.jp>"]
license = "MIT"
readme = "README.md"
packages = [
    { "include"="server" }
]

[tool.poetry.scripts]
server = 'main:run'

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.85.0"
fastapi-sso = {git = "https://github.com/maru0123-2004/fastapi-sso"}
SQLAlchemy-Utils = "^0.38.3"
passlib = "^1.7.4"
alembic = "^1.8.1"
aiofiles = "^22.1.0"
pydantic-geojson = "^0.0.3"


[tool.poetry.group.dev.dependencies]
fastapi = {extras = ["all"], version = "^0.85.0"}
aiosqlite = "^0.17.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
